cc_test(
  name = "multiple_currency_test",
  size = "small",
  srcs = ["bank.hpp", "money.hpp", "multiple_currency_test.cpp"],
  deps = ["@com_google_googletest//:gtest_main"],
  copts = ["--std=c++17"],
)