cc_test(
  name = "multiple_currency_test",
  size = "small",
  srcs = ["bank.h", "expression.h", "money.h",  "sum.h", "multiple_currency_test.cc"],
  deps = ["@com_google_googletest//:gtest_main"],
  copts = ["--std=c++17"],
)