name: Simple CI

on: [pull_request, push]

jobs:
  tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: bazel test --test_output=all //chapter-1:test
    - run: bazel test --test_output=all //chapter-2:test
    - run: bazel test --test_output=all //chapter-3:test
    - run: bazel test --test_output=all //chapter-4:test
    - run: bazel test --test_output=all //chapter-5:test

  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install clang-format
    - name: check
      run: bash scripts/clang_format_test.sh .

  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install python3-pip && sudo pip3 install cpplint
    - name: check
      run: bash scripts/cpplint.sh .
