name: Simple CI

on: [pull_request, push]

jobs:
  tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: bazel test --test_output=all //chapter-01:test
    - run: bazel test --test_output=all //chapter-02:test
    - run: bazel test --test_output=all //chapter-03:test
    - run: bazel test --test_output=all //chapter-04:test
    - run: bazel test --test_output=all //chapter-05:test
    - run: bazel test --test_output=all //chapter-06:test
    - run: bazel test --test_output=all //chapter-07:test
    - run: bazel test --test_output=all //chapter-08:test
    - run: bazel test --test_output=all //chapter-09:test
    - run: bazel test --test_output=all //chapter-10:test

  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install clang-format
    - name: check
      run: bash tools/scripts/clang_format_test.sh .

  cpplint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install python3-pip && sudo pip3 install cpplint
    - name: check
      run: bash tools/scripts/cpplint.sh .
