name: Simple CI

on: [pull_request, push]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt-get update && sudo apt-get install clang-format
    - name: check
      run: bash scripts/clang_format_test.sh .
